# Dockerfile for building base animal_farm image
FROM ubuntu:18.04

RUN apt update \
  && apt install software-properties-common -y \
  && add-apt-repository ppa:deadsnakes/ppa \
  && apt install python3.6

RUN apt update \
  && apt install python3-pip -y

RUN cd /usr/local/bin \
  && ln -s /usr/bin/python3 python

RUN apt install default-libmysqlclient-dev -y

RUN pip3 install django
RUN pip3 install gunicorn
RUN pip3 install mysqlclient
RUN pip3 install pyyaml